Fix eleven-ultralegacy-devices picks
Default manifest hasn't switched to LOS repos for art & perfetto yet resulting in:

ERROR: For 286185, could not determine the project path for project LineageOS/android_art
ERROR: For 287706, could not determine the project path for project LineageOS/android_external_perfetto

This reverts commit 183ec7caf3f4ca06ae52f5ddfc2d1b93322980a8.